const data = [
  {
    id: 1,
    imgUrl: 'https://i.ibb.co/n11fr31/Rectangle-9.png',
    productName: 'Smashed Avo',
    productPrice: 379,
    subtitle: '',
    ordered: 0,
  },
  {
    id: 2,
    imgUrl: 'https://i.ibb.co/MsWtQy9/Rectangle-10-1.png',
    productName: 'Yin & Yang',
    productPrice: 225,
    subtitle: '',
    ordered: 0,
  },
  {
    id: 3,
    imgUrl: 'https://i.ibb.co/JmhKxNd/Rectangle-11.png',
    productName: 'Pancakes',
    productPrice: 170,
    subtitle: '',
    ordered: 0,
  },
  {
    id: 4,
    imgUrl: 'https://i.ibb.co/FJQRB5T/Rectangle-12.png',
    productName: 'Huevos Rancheros',
    productPrice: 150,
    subtitle: '',
    ordered: 0,
  },
  {
    id: 5,
    imgUrl: 'https://i.ibb.co/FwQqtNb/Rectangle-13-1.png',
    productName: 'Rancheros (Tofu)',
    productPrice: 180,
    subtitle: '',
    ordered: 0,
  },
  {
    id: 6,
    imgUrl: 'https://i.ibb.co/3CDncVy/Rectangle-14.png',
    productName: 'Breakkie Roll',
    productPrice: 300,
    subtitle: '',
    ordered: 0,
  },
  {
    id: 7,
    imgUrl: 'https://i.ibb.co/X5hQb16/Rectangle-15.png',
    productName: 'Breakkie Roll',
    productPrice: 340,
    subtitle: '',
    ordered: 0,
  },
  {
    id: 8,
    imgUrl: 'https://i.ibb.co/Pc1D8DG/Rectangle-16.png',
    productName: 'Burrito',
    productPrice: 420,
    subtitle: '',
    ordered: 0,
  },
];

export default data;
